### PR TITLE
Only use travis

### PR DESCRIPTION
**Pull request by dneise**
This is a previous state of #28, which does not modify optimization.

This PR tries to accomplish this:

 - use a `.travis.yml` file in order to show how to build and test this project.
 - adjust the README file to reflect exactly the same things, as are done in the `travis.yml` file
 - (modify the line endings of the README file from windows to linux, makes diff large, view diff with "ignore whitespace changes")

This PR does change the `CMakeLists.txt` even though this should not be needed at all, the CMakeLists worked before locally on my machine. But it did not work on travis...

We believe it was aged, so while many comments talked about C++11, actually C++17 is needed now, so this was changed of course. The other thing, which was changed in that file, was the moving of line 3 to line 10, which seemed necessary to make the thing work on travis.

### CODE REVIEW

**Comment by dneise** [comment]
In this build one can see, what happened on travis, when we did not modify the CMakeLists:

https://travis-ci.org/cherenkov-plenoscope/merlict_development_kit/builds/516096173#L734

**Comment by dneise** [comment]
Ah .. so codecov is yellow here, since this PR totally ignores codecov.

**Comment by dneise** [comment]
Screenshot from 2019-04-08 14-42-38

Maybe the easiest way to look at the diff of the README is as "rich diff"

**Comment by mahnen** [comment]
Sry, there was a strang setting with signed commits.. seemed to be different from committing with your account email / sha-public key.

**Pull request merged**
