### PR TITLE
WIP: Wrap with swig

### PR DESCRIPTION
**Pull request by dneise**
This PR is currently work in progress, but I opened it already, so interested people can have a look at the progress and also the direction this is going. 

In case this goes in a wrong direction, early feedback is appreciated :-D

**Note** This PR depends on a couple of currently open PRs, so its diff looks larger than it is. I recommend to first look at PR #28 (travis) and at #32 (one_source.py). So that this PRs diff becomes smaller.

What this is about and how to try it out, I've described in the README. I did not want to touch the C-sources, but I had to, see .e.g #34.

### CODE REVIEW

**Comment by dneise** [comment]
Ah SWIG is not pip installable .. so we'll have to use conda I assume ... 
So I'll install miniconda and use py3.7 from now on.

**Comment by dneise** [comment]
Okay Yeah!

So. I use conda now, to install python, gcc and g++ and SWIG. The gcc installed by conda cannot be called as `gcc` but as `$GCC`, details can be found here: 

https://www.anaconda.com/utilizing-the-new-compilers-in-anaconda-distribution-5/

This took some time for me to understand...

cmake and `setup.py` use the `GCC` and `GXX` environment variables by default, I think .. so this is not a problem, the only problem is if one types: "gcc" on the command line and expects to get the compiler which was installed by conda. 

---

So ... the build works now (I leave out the cmake build for the moment, since it takes 5min to run)
Also wrapping works (in the sense that it compiles and can be `import`et).
But the single unit test, which I played with at the moment .. fails. 

None of the photons is detected by the absorber sensor, but this is identical to the state on my machine...so in a sense travis confirms my current local state.
Here one can see the failing test \o/ :+1: 

https://travis-ci.org/cherenkov-plenoscope/merlict_development_kit/builds/517727635#L1143

As one can see, all the lines above .. run without throwing exceptions ... so far so bad :-D.

---

As a next step, I believe I would play with less advanced unit tests and see if I can get a few of them to work. However, If anybody else would like to play with this state here? We could also discuss to merge this, despite the failing test, so that we all can play ... but only if your want.

**Comment by dneise** [comment]
@relleums @mahnen please have a look at the last comment.

**Comment by dneise** [comment]
Okay so next steps are simple ... copy all units tests from `merlict/tests/*Test.cpp` to `tests/test_*.py` files in the same order as they are in the CPP files as transparent as possible, in order to avoid mental mapping.

**Comment by dneise** [comment]
Help is greatly appreciated here. I will not have time to work on this PR until the weekend, so whoever wants to add some unit tests is very welcome to just push into this branch here.

**Comment by relleums** [comment]
Closed. I failed to push the python integration. In the meantime SWIG is kind of obsolete.

**Pull request closed without merging**
